/image2rtsp:
   ros__parameters:

      # If camera serves as a source
      camera: False
      source: "v4l2src device=/dev/video0"

      # If the source is a ros2 topic (default case)
      compressed_image: False
      topic: "/image"

      # General setup
      mountpoint: "/test12_BGR"
      bitrate: "400"
      framerate: "30"
      caps_1: "video/x-raw, framerate ="
      caps_2: "/1, width=426,height=240"
      port: "8554"
      local_only: False     # True = rtsp://127.0.0.1:portAndMountpoint (The stream is accessible only from the local machine)
                           # False = rtsp://0.0.0.0:portAndMountpoint (The stream is accessible from the outside) 
                           # For example, to access the stream running on the machine with IP = 192.168.20.20,
                           # use rtsp://192.186.20.20:portAndMountpoint

      override_pipeline: True      
      custom_pipeline: "( appsrc name=imagesrc do-timestamp=true is-live=true ! video/x-raw, format=BGR, width=640, height=480, framerate=30/1 ! videoconvert ! videoscale ! video/x-raw, format=I420, width=640, height=480 ! x264enc tune=zerolatency bitrate=500 key-int-max=30 ! rtph264pay name=pay0 pt=96 )"
